# Generated by Django 2.2.2 on 2019-06-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=252)),
                ('file_md5', models.CharField(max_length=128)),
                ('file_type', models.CharField(max_length=32)),
                ('file_size', models.IntegerField()),
            ],
            options={
                'db_table': 'upload_image',
            },
        ),
    ]
