# Generated by Django 2.2.2 on 2019-06-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20190625_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='updated_at',
        ),
    ]
