# Generated by Django 2.2.2 on 2019-06-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='touxiang',
            field=models.CharField(default='', max_length=100),
        ),
    ]
