# Generated by Django 3.0 on 2019-06-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userid',
        ),
    ]
